// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf90KlGLM9PSZWdi_SIq2VkLplqRWQrCg',
    appId: '1:6173983291:web:0a2e8fb48e3621b03e921e',
    messagingSenderId: '6173983291',
    projectId: 'nguyenindoubt-app',
    authDomain: 'nguyenindoubt-app.firebaseapp.com',
    storageBucket: 'nguyenindoubt-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEM9ABH1UedhiGhWWEOgigFvTdfytCqt0',
    appId: '1:6173983291:android:6b3849f3af9c1af23e921e',
    messagingSenderId: '6173983291',
    projectId: 'nguyenindoubt-app',
    storageBucket: 'nguyenindoubt-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoIXzyl_N7e3GFNpz1Dtli11ShlzObEDQ',
    appId: '1:6173983291:ios:c0810af3fc3e291f3e921e',
    messagingSenderId: '6173983291',
    projectId: 'nguyenindoubt-app',
    storageBucket: 'nguyenindoubt-app.firebasestorage.app',
    iosClientId:
        '6173983291-kndcs876odq1cgcbaq8u6jgqhj9rv3dc.apps.googleusercontent.com',
    iosBundleId: 'com.nguyenindoubt.nguyenindoubtApp',
  );
}
